"""add_notifications

Revision ID: 17990e6d0210
Revises: abc1add0sched
Create Date: 2026-03-14 15:14:44.819117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17990e6d0210"
down_revision: Union[str, Sequence[str], None] = "abc1add0sched"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "channel"),
    )
    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_preferences_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notification_preferences_player_id"), ["player_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tag", sa.String(length=32), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_event_id"), ["event_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_player_id"), ["player_id"], unique=False)

    op.create_table(
        "web_push_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("endpoint", sa.String(length=512), nullable=False),
        sa.Column("p256dh_key", sa.String(length=256), nullable=False),
        sa.Column("auth_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("web_push_subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_web_push_subscriptions_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_web_push_subscriptions_player_id"), ["player_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_push_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_web_push_subscriptions_player_id"))
        batch_op.drop_index(batch_op.f("ix_web_push_subscriptions_id"))

    op.drop_table("web_push_subscriptions")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_player_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_event_id"))

    op.drop_table("notifications")
    with op.batch_alter_table("notification_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_preferences_player_id"))
        batch_op.drop_index(batch_op.f("ix_notification_preferences_id"))

    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
