"""initial schema

Revision ID: 7d6728f4bc65
Revises: 
Create Date: 2026-03-05 16:04:04.099957

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7d6728f4bc65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_token_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_season_id'), ['season_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('event_end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('meeting_time', sa.Time(), nullable=True),
    sa.Column('meeting_location', sa.String(length=256), nullable=True),
    sa.Column('presence_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('recurrence_group_id', sa.String(length=36), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=32), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_recurrence_group_id'), ['recurrence_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_team_id'), ['team_id'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=False)

    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_id', name='uq_attendance_event_player')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_player_id'), ['player_id'], unique=False)

    op.create_table('player_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('relationship_label', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone2', sa.String(length=32), nullable=True),
    sa.Column('street', sa.String(length=256), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_contacts_player_id'), ['player_id'], unique=True)

    op.create_table('player_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_phones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_phones_player_id'), ['player_id'], unique=False)

    op.create_table('player_teams',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('membership_status', sa.String(length=16), nullable=False),
    sa.Column('injured_until', sa.Date(), nullable=True),
    sa.Column('absent_by_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'team_id'),
    sa.UniqueConstraint('player_id', 'team_id', name='uq_player_team')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_teams')
    with op.batch_alter_table('player_phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_phones_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_phones_id'))

    op.drop_table('player_phones')
    with op.batch_alter_table('player_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_contacts_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_contacts_id'))

    op.drop_table('player_contacts')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_player_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_event_id'))

    op.drop_table('attendances')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_user_id'))
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_id'))
        batch_op.drop_index(batch_op.f('ix_players_email'))

    op.drop_table('players')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_team_id'))
        batch_op.drop_index(batch_op.f('ix_events_season_id'))
        batch_op.drop_index(batch_op.f('ix_events_recurrence_group_id'))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_date'))

    op.drop_table('events')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_season_id'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_id'))

    op.drop_table('seasons')
    # ### end Alembic commands ###
