"""add telegram_notifications table

Revision ID: c62dbb009a96
Revises: r6s7t8u9v0w1
Create Date: 2026-04-22 11:40:05.602184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62dbb009a96'
down_revision: Union[str, Sequence[str], None] = 'r6s7t8u9v0w1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'telegram_notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.Index(sa.text('ix_telegram_notifications_created_at'), 'created_at'),
        sa.Index(sa.text('ix_telegram_notifications_event_id'), 'event_id'),
        sa.Index(sa.text('ix_telegram_notifications_player_id'), 'player_id'),
        sa.Index(sa.text('ix_telegram_notifications_user_id'), 'user_id'),
    )

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_players_user_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_players_user_id'))
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id_unique'))
        batch_op.create_unique_constraint(None, ['telegram_chat_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id_unique'), ['telegram_chat_id'], unique=1)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_user_id'))
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_players_user_id'), ['user_id'])

    op.drop_table('telegram_notifications')
    # ### end Alembic commands ###
