"""add telegram_notifications table

Revision ID: c62dbb009a96
Revises: r6s7t8u9v0w1
Create Date: 2026-04-22 11:40:05.602184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62dbb009a96'
down_revision: Union[str, Sequence[str], None] = 'r6s7t8u9v0w1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_players_user_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_players_user_id'))
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id_unique'))
        batch_op.create_unique_constraint(None, ['telegram_chat_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id_unique'), ['telegram_chat_id'], unique=1)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_user_id'))
        batch_op.create_index(batch_op.f('ix_players_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_players_user_id'), ['user_id'])

    # ### end Alembic commands ###
